#! /bin/bash
runhand(){
    logtime=$(date)
    echo '>> analyzing file:' $1
    cmsRun h2testbeamanalyzer_cfgbk.py $1 >/dev/null 
    root -l -q -b "plotPulseProfile.cc(\"${1:17:6}\")" >/dev/null 
    root -l -q -b "plotCapIDvsBXProfile.cc(\"${1:17:6}\")" >/dev/null 
    echo '>> file' $1 analyzed
    cat > ~/www/904LED/run_${1:17:6}/run.log<<EOF
LED run data file: 
       hcal904daq01:/tmp/$1
generated at: 
       $logtime
EOF
    isfi=$(lsof|grep $1)
    if [ -z "$isfi" ];then
	rm *${1:17:6}.root
    fi
}

runcpfile(){
    st=$(ssh cms904usr bin/cpLED |grep B904)
    if [ -n "$st" ]
    then
	date
	echo '>> copying file: '
	scp cms904usr:./B904* ~/work/public/cms904/
	ssh cms904usr 'rm ./B904*'
	echo '>> sending email'
	mail -s 'LED data' yw5mj@virginia.edu<<EOF
found LED data file:
$st

Data has been copied to yanchuwang.cern.ch
Analyzing is in process
EOF
	for f in $st
	do
	    runhand $f &
	done
    fi
}

if [ "$1" == "-i" ]
then
    scp stlog cpLED cms904usr:bin/
    exit
fi
if [ "$1" == "-s" ]
then
    if [ -z "$2" ]
    then
	stm=$(date -d @$(($(date +%s)-86400)) +%m%d%H%M)
    else
	stm=$2
    fi
    ssh cms904usr touch -t $stm bin/cpLED
    ssh cms904usr 'ssh hcal904daq01 touch /tmp/timecheck.log'
    exit
fi

set -e
cd /afs/cern.ch/user/y/yanchu/work/cms904/CMSSW_7_5_0_pre5/src/HFcommissioning/Analysis/test
eval `scramv1 runtime -sh`
echo '>> set CMSSW environment successfully'
set +e

while :
do
    ssh cms904usr 'bin/stlog >/dev/null'
    runcpfile 2>>~/cpfile.log
    sleep 10
done

