#! /bin/bash
runhand(){
    echo '>> analyzing file:' $1
    cmsRun h2testbeamanalyzer_cfgbk.py $1 >/dev/null 
    isfi=$(lsof|grep $1)
    if [ -z "$isfi" ];then
	root -l -q -b "plotPulseProfile.cc(\"${1:20:3}\")" >/dev/null 
	root -l -q -b "plotCapIDvsBXProfile.cc(\"${1:20:3}\")" >/dev/null 
	echo '>> file' $1 analyzed
	rm *${1:20:3}.root
    fi
}

runcpfile(){
    st=$(ssh cms904usr bin/cpLED $1|grep B904)
    if [ -n "$st" ]
    then
	date
	echo '>> copying file: '
	scp cms904usr:./B904* ~/work/public/cms904/
	ssh cms904usr 'rm ./B904*'
	for f in $st
	do
	    runhand $f &
	done
    fi
}

if [ "$1" == "-i" ]
then
    scp stlog cpLED cms904usr:bin/
    exit
fi

set -e
cd /afs/cern.ch/user/y/yanchu/work/cms904/CMSSW_7_5_0_pre5/src/HFcommissioning/Analysis/test
eval `scramv1 runtime -sh`
set +e
if [ "$1" == "-s" ]
then
    runcpfile $((24*60))
    exit
fi

while :
do
    ssh cms904usr 'bin/stlog >/dev/null'
    runcpfile 2>>~/cpfile.log
    sleep 10
done

