#! /bin/bash
if [ "$HOSTNAME" == 'vmepc-e1x07-06-01' ];then
    newfile=$(find /tmp -newer $0 2>/dev/null)	    
    isend=$(echo "$newfile" |grep timecheck.log)	    
    tocp=$(echo "$newfile" |grep B904_Integration)	
    touch $0
    if [ -n "$isend" ]&&[ -n "$tocp" ];then
	echo "moving file:"
	for fl in $tocp
	do
	    echo "$fl"|cut -c6-
	    cp $fl ~
	done
    else
	echo "warning: no matched file"
    fi
else
    ssh hcal904daq01 $0 $*
fi

