#! /bin/bash
if [ "$HOSTNAME" == 'vmepc-e1x07-06-01' ];then
    if [ -z $1 ]
    then
	tocp=$(find /tmp -newer $0 2>/dev/null |grep B904_Integration)	
	touch $0
    else
	tocp=$(find /tmp -cmin -$1 2>/dev/null |grep B904_Integration)
    fi
    if [ -n "$tocp" ];then
	echo "moving file:"
	for fl in $tocp
	do
	    echo "$fl"|cut -c6-
	    cp $fl ~
	done
    else
	echo "warning: no matched file"
    fi
else
    ssh hcal904daq01 $0 $*
fi

